url: "https://marchfelderboehmische.at"
title: "Marchfelder Böhmische"
tagline: "Böhmisch-Mährische Blasmusik"
description: "Böhmisch-Mährische Blasmusik aus dem Herzen des Marchfelds"
locale: "de_AT"
logo: "/assets/img/logo.png"
social:
  name: Marchfelder Böhmische
  links:
    - https://www.facebook.com/MarchfelderBoehmische
    - https://www.instagram.com/marchfelderboehmische
    - https://www.youtube.com/@marchfelderboehmische

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
