url: "https://marchfelderboehmische.at"
title: "Marchfelder Böhmische"
tagline: "Böhmisch-Mährische Blasmusik aus dem Herzen des Marchfelds"
description: "Die zwölf Musikanten, darunter auch zwei Mädels der Marchfelder Böhmischen (bestehend aus drei Flügelhörnern, zwei Tenorhörnern, zwei Klarinetten, zwei Trompeten, einer Posaune, einer Tuba und einem Schlagwerk) musizieren bereits seit einiger Zeit miteinander und gründeten die Gruppe im Herbst 2022. Das liegt wohl an der Dynamik der Musikant:innen; acht der zwölf Mitglieder sind unter 30 Jahre alt und leisten bzw. haben ihren Präsenzdienst bei der Gardemusik Wien abgeleistet. Unabhängig vom Alter haben sie eines gemeinsam, die Begeisterung und Passion zur traditionellen böhmisch-mährischen Blasmusik. Zu dem Repertoire der Gruppe gehören Polkas, Walzer und Märsche aus Österreich, Tschechien und der Slowakei. Jene Musikstücke sind aus der Blasmusikkultur des Marchfeldes nicht mehr wegzudenken und werden unter anderem bei Frühschoppen zum Besten gegeben. Bereits einige solche Frühschoppen durfte die Marchfelder Böhmische, unter anderem bei den Marchfeldtagen in Wien am Hof und somit die Region Marchfeld vertreten und repräsentieren, gestalten."
locale: "de_AT"
logo: "/assets/img/logo.png"
social:
  name: Marchfelder Böhmische
  links:
    - https://www.facebook.com/MarchfelderBoehmische
    - https://www.instagram.com/marchfelderboehmische
    - https://www.youtube.com/@marchfelderboehmische

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
